/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSourcesRouteImport } from './routes/_app.sources'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppIntelligenceRouteImport } from './routes/_app.intelligence'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyzeRouteImport } from './routes/_app.analyze'
import { Route as AppReportsIdRouteImport } from './routes/_app.reports.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzeRoute = AppAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIdRoute = AppReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AppAnalyzeRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/reports/$id': typeof AppReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AppAnalyzeRoute
  '/dashboard': typeof AppDashboardRoute
  '/history': typeof AppHistoryRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/sources': typeof AppSourcesRoute
  '/reports/$id': typeof AppReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/analyze': typeof AppAnalyzeRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/intelligence': typeof AppIntelligenceRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sources': typeof AppSourcesRoute
  '/_app/reports/$id': typeof AppReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/history'
    | '/intelligence'
    | '/reports'
    | '/settings'
    | '/sources'
    | '/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/history'
    | '/intelligence'
    | '/reports'
    | '/settings'
    | '/sources'
    | '/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/analyze'
    | '/_app/dashboard'
    | '/_app/history'
    | '/_app/intelligence'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intelligence': {
      id: '/_app/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analyze': {
      id: '/_app/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AppAnalyzeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/$id': {
      id: '/_app/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AppReportsIdRouteImport
      parentRoute: typeof AppReportsRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsIdRoute: typeof AppReportsIdRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsIdRoute: AppReportsIdRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyzeRoute: typeof AppAnalyzeRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSourcesRoute: typeof AppSourcesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyzeRoute: AppAnalyzeRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSourcesRoute: AppSourcesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
